#! /usr/bin/env python
# encoding: utf-8
# a1batross, mittorn, 2018

from waflib import Utils
import os

def options(opt):
	grp = opt.add_option_group('Client options')

	grp.add_option('--enable-pman', action = 'store_true', dest = 'USE_PMAN', default = False,
		help = 'Enable Particleman')
	grp.add_option('--disable-goldsrc-support', action = 'store_false', dest = 'GOLDSOURCE_SUPPORT',
		default=True, help = 'disable GoldSource compatibility on i386 Win/Mac/Linux')

	opt.load('vgui')

def configure(conf):
	conf.env.USE_PMAN= conf.options.USE_PMAN
	conf.env.USE_VOICEMGR = conf.options.USE_VOICEMGR

	if (conf.env.DEST_CPU == 'x86' or (conf.env.DEST_CPU == 'x86_64' and not conf.options.ALLOW64)) and conf.env.DEST_OS in ['win32', 'linux', 'darwin']:
		conf.env.GOLDSOURCE_SUPPORT = conf.options.GOLDSOURCE_SUPPORT
	else:
		conf.env.GOLDSOURCE_SUPPORT = False

	if conf.env.GOLDSOURCE_SUPPORT and not conf.env.DEST_OS == 'win32':
		conf.check_cc(lib='dl')

def build(bld):
	libs = ['vcs_info']
	defines = ['CLIENT_DLL']
	defines += bld.env.EXPORT_DEFINES_LIST
	includes = ['.',
		'../dlls',
		'../common',
		'../engine',
		'../pm_shared',
		'../game_shared',
		'../public']
	excluded_files = ['GameStudioModelRenderer_Sample.cpp',
		'game_shared/voice_vgui_tweakdlg.cpp',
		'game_shared/voice_gamemgr.cpp',
		'game_shared/voice_status.cpp']

	if bld.env.USE_PMAN:
		defines += ['USE_PMAN']
		libs += ['Particleman']
		includes['../3rdparty/particleman',
		   '../3rdparty/particleman/common',
		   '../3rdparty/particleman/dlls',
		   '../3rdparty/particleman/engine',
		   '../3rdparty/particleman/particleman/particlefx_header',
		   '../3rdparty/particleman/particleman/pm_shared',
		   '../3rdparty/particleman/pm_shared',
		   '../3rdparty/particleman/public']
		excluded_files += ['../3rdparty/particleman/particleman/particlefx_source/*.cpp']

	source = bld.path.ant_glob('**/*.cpp', excl=excluded_files)
	source += bld.path.parent.ant_glob('game_shared/*.cpp', excl=excluded_files)
	source += bld.path.parent.ant_glob([
		'public/safe_snprintf.c',
		'pm_shared/*.c',
		'dlls/wpn_shared/*.cpp',
		'dlls/dod_shared.cpp'
	])


	if bld.env.DEST_OS == 'win32':
		libs += ['USER32']

	if bld.env.GOLDSOURCE_SUPPORT:
		defines += ['GOLDSOURCE_SUPPORT']
		includes += ['../external/']

		if bld.env.DEST_OS == 'win32':
			libs += ["WINMM"]
		else:
			libs += ['DL']

	if 'HAVE_STRLCPY=1' not in defines:
		source += bld.path.parent.ant_glob('external/openbsd/strlcpy.c')

	if 'HAVE_STRLCAT=1' not in defines:
		source += bld.path.parent.ant_glob('external/openbsd/strlcat.c')

	if bld.env.DEST_OS != 'dos' and not bld.env.ANDROID_APK:
		install_path = os.path.join(bld.env.GAMEDIR, bld.env.CLIENT_INSTALL_DIR)
	else:
		install_path = bld.env.PREFIX

	bld.shlib(
		source   = source,
		target   = 'client' + bld.env.POSTFIX,
		name     = 'client',
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		idx = bld.get_taskgen_count()
	)

